### ISSUE TITLE
Merge with balena-fin-firmata-flash

### ISSUE THREAD

**Issue by martenjacobs** [balena-io/balena-fin-coprocessor-firmata#14]
Are there any plans to merge this repo with [this one](https://github.com/balena-io-playground/balena-fin-firmata-flash)? 

Looking at the current practice in other balena projects of having a build container and a run container in a single Dockerfile, I'd say we could simply add a Dockerfile to this repo that will first compile in a build container and then create a second container that will deploy the resulting binaries to the target devices. 

We'd only need to move some files around and move over some files from the `balena-fin-firmata-flash` repo. I could put together a PR if that'd help.

**Comment by Bucknalla** [comment]
Hi @martenjacobs,
The main reason we're keeping them seperate is so that we can maintain a consistent base repository for the firmata firmware (C & C++ libraries). This repository is only for tracking the source of the coprocessor firmata project.

The intention is that you'll be able to point your Dockerfile at the release page, pull the latest compiled binary and use that to flash the coprocessor, as is done in the `balena-fin-firmata-flash` repo on the v1.1.-beta2 branch (https://github.com/balena-io-playground/balena-fin-firmata-flash/tree/v1.1-beta2).

**Comment by martenjacobs** [comment]
Okay, that makes sense for users who simply want to deploy the pre-made firmware. My use case is a little different: I’ve added a sysex command to a fork of the firmware and would like to deploy it through balenaCloud down to my devices. I understand that may not be what you're aiming to do here, so I'll roll my own.
